Dune::Multiscale::LocalProblemOperator Class Reference
Dune::Multiscale::LocalProblemOperator Class Reference
#include <dune/multiscale/msfem/localproblems/localoperator.hh>
Public Member Functions
LocalProblemOperator (const DMP::ProblemContainer &problem, const CommonTraits::SpaceType &coarse_space, const MsFEMTraits::LocalSpaceType &subDiscreteFunctionSpace)
void assemble_all_local_rhs (const MsFEMTraits::CoarseEntityType &coarseEntity, MsFEMTraits::LocalSolutionVectorType &allLocalRHS)
void apply_inverse (const MsFEMTraits::LocalGridDiscreteFunctionType &current_rhs, MsFEMTraits::LocalGridDiscreteFunctionType &current_solution)
Constructor & Destructor Documentation
Dune::Multiscale::LocalProblemOperator::LocalProblemOperator (const DMP::ProblemContainer & problem, const CommonTraits::SpaceType & coarse_space, const MsFEMTraits::LocalSpaceType & subDiscreteFunctionSpace)
Member Function Documentation
void Dune::Multiscale::LocalProblemOperator::apply_inverse (const MsFEMTraits::LocalGridDiscreteFunctionType & current_rhs, MsFEMTraits::LocalGridDiscreteFunctionType & current_solution)
References Dune::Multiscale::Problem::ProblemContainer::config().
void Dune::Multiscale::LocalProblemOperator::assemble_all_local_rhs (const MsFEMTraits::CoarseEntityType & coarseEntity, MsFEMTraits::LocalSolutionVectorType & allLocalRHS)
Assemble right hand side vectors for all local problems on one coarse cell.
Parameters
[in] coarseEntity The coarse cell.
[out] allLocalRHS A vector with pointers to the discrete functions for the right hand sides.
Note
The vector allLocalRHS is assumed to have the correct size and contain pointers to all local rhs functions. The discrete functions in allLocalRHS will be cleared in this function.
References Dune::Multiscale::Problem::ProblemContainer::config(), Dune::Multiscale::Problem::ProblemContainer::getDiffusion(), Dune::Multiscale::Problem::ProblemContainer::getNeumannData(), and Dune::Stuff::Grid::is_simplex_grid().
The documentation for this class was generated from the following files:
localoperator.hh
localoperator.cc