Dune::Multiscale Namespace Reference
Dune::Multiscale Namespace Reference
Namespaces
Problem
Classes
struct IOTraits
class DiskBackend
class MemoryBackend
simple discrete function to disk writer this class isn't type safe in the sense that different appends may append non-convertible discrete function implementations
class DiscreteFunctionIO
class ErrorCalculator
class MsFEMProjection
struct BackendChooser
class MyGridFactory
Helper struct to make overlap for SPGrid possible.
struct LocalGridFactory
class MyGridFactory< Dune::SPGrid< ct, dim, Refinement, Comm > >
class MyGridFactory< Dune::YaspGrid< dim, Coord > >
struct SpaceChooser
struct CommonTraits
Common Types, duh.
class RhsCodim0IntegralTraits
class RhsCodim0VectorTraits
class RhsCodim0Integral
class RhsCodim0Vector
class CoarseRhsFunctionalTraits
class CoarseRhsFunctional
class MsFEMCodim0IntegralTraits
class MsFemCodim0MatrixTraits
class MsFEMCodim0Integral
class MsFemCodim0Matrix
class CoarseScaleOperatorTraits
class CoarseScaleOperator
class ProductTraitsBase
Traits for the Product evaluation.
struct CoarseBasisProductTraits
class CoarseBasisProduct
struct DirichletProductTraits
Traits for the Product evaluation.
class DirichletProduct
class Elliptic_FEM_Solver
class LocalGridList
container for cell problem subgrids
class LocalGridSearch
given a Localgridlist, facilitate searching for evaluation points in a pseudo-hierachical manner
class BoundaryValueHelper
holds functionals,etc for boundary correctors to make conditional usage simpler
class LocalProblemOperator
struct LocalProblemDataOutputParameters
define output parameters for local problems appends "local_problems" for path
class LocalProblemSolver
the essential local msfem problem solver class
class LocalSolutionManager
One LocalSolutionManager instance per coarse cell.
class LocalsolutionProxy
class Elliptic_MsFEM_Solver
needs a better name
struct LocalGridChooser
struct LocalGridChooser< Dune::YaspGrid< CommonTraits::world_dim, Dune::EquidistantOffsetCoordinates< double, CommonTraits::world_dim > > >
struct MsFEMTraits
type construction for the MSFEM code
struct ProxyGridviewTraits
class ProxyGridview
struct OutputParameters
define output parameters for Dune::DataOutput
Functions
std::pair< std::shared_ptr
< CommonTraits::GridType >
, std::shared_ptr
< CommonTraits::GridType > > make_grids (const DMP::ProblemContainer &problem, const bool check_partitioning=true, Dune::MPIHelper::MPICommunicator communicator=Dune::MPIHelper::getCommunicator())
abstraction for creating coarse and fine grid instances. shared across msfem/fem codes.
std::shared_ptr
< CommonTraits::GridType > make_fine_grid (const DMP::ProblemContainer &problem, std::shared_ptr< CommonTraits::GridType > coarse_gridptr=nullptr, bool check_partitioning=true, Dune::MPIHelper::MPICommunicator communicator=Dune::MPIHelper::getCommunicator())
std::shared_ptr
< CommonTraits::GridType > make_coarse_grid (const DMP::ProblemContainer &problem, Dune::MPIHelper::MPICommunicator communicator=Dune::MPIHelper::getCommunicator())
template<class ImpTraits , size_t domainDim, size_t rangeDim>
std::vector< typename
GDT::Spaces::CGInterface
< ImpTraits, domainDim,
rangeDim, 1 >::DomainType > global_evaluation_points (const GDT::Spaces::CGInterface< ImpTraits, domainDim, rangeDim, 1 > &space, const typename GDT::Spaces::CGInterface< ImpTraits, domainDim, rangeDim, 1 >::EntityType &target_entity)
void init (int argc, char **argv)
setup code common to fem/msfem/hmm
int handle_exception (const Dune::Exception &exp)
int handle_exception (const std::exception &exp)
int handle_exception (const tbb::tbb_exception &exp)
void mem_usage ()
void dump_environment ()
template<class T = CommonTraits::DiscreteFunctionType>
std::shared_ptr< T > make_df_ptr (const std::string name, const typename T::SpaceType &space)
std::map< std::string, double > cgfem_algorithm ()
the main FEM computation
void write_discrete_function (const DMP::ProblemContainer &problem, CommonTraits::DiscreteFunction_ptr &discrete_solution, const std::string prefix)
write discrete function VTK Output
void print_info (const Problem::ProblemContainer &problem, std::ostream &out)
outputs Problem info to output stream
void write_discrete_function (CommonTraits::DiscreteFunctionType &discrete_solution, const std::string prefix)
std::map< std::string, double > msfem_algorithm ()
algorithm
template<class FunctionType >
void output_all (std::vector< std::unique_ptr< FunctionType >> &functions, CommonTraits::GridViewType &view, std::string name)
void partition_vis_single (CommonTraits::GridType &grid, std::string function_name)
template<class T >
unsigned long id_to_ulong (const T &id)
template<int k>
unsigned long id_to_ulong (const Dune::bigunsignedint< k > &id)
void subgrid_vis (DMP::ProblemContainer &problem, CommonTraits::GridType &coarse_grid, CommonTraits::GridType &fine_grid)
void partition_vis (CommonTraits::GridType &coarse_grid, CommonTraits::GridType &fine_grid)
Function Documentation
std::map< std::string, double > Dune::Multiscale::cgfem_algorithm ()
the main FEM computation
References Dune::Multiscale::Problem::ProblemContainer::config(), Dune::Multiscale::Problem::ProblemContainer::getMutableModelData(), Dune::Multiscale::Problem::IModelProblemData::prepare_new_evaluation(), Dune::Multiscale::ErrorCalculator::print(), problem(), Dune::Multiscale::OutputParameters::set_prefix(), Dune::Multiscale::Elliptic_FEM_Solver::solve(), and Dune::Multiscale::CommonTraits::world_dim.
Referenced by main().
void Dune::Multiscale::dump_environment ()
Referenced by main().
template<class ImpTraits , size_t domainDim, size_t rangeDim> std::vector<typename GDT::Spaces::CGInterface<ImpTraits, domainDim, rangeDim, 1>::DomainType> Dune::Multiscale::global_evaluation_points (const GDT::Spaces::CGInterface< ImpTraits, domainDim, rangeDim, 1 > & space, const typename GDT::Spaces::CGInterface< ImpTraits, domainDim, rangeDim, 1 >::EntityType & target_entity)
Referenced by Dune::Multiscale::MsFEMProjection::project().
int Dune::Multiscale::handle_exception (const Dune::Exception & exp)
References mem_usage().
Referenced by main().
int Dune::Multiscale::handle_exception (const std::exception & exp)
References mem_usage().
int Dune::Multiscale::handle_exception (const tbb::tbb_exception & exp)
References mem_usage().
template<class T > unsigned long Dune::Multiscale::id_to_ulong (const T & id)
Referenced by subgrid_vis().
template<int k> unsigned long Dune::Multiscale::id_to_ulong (const Dune::bigunsignedint< k > & id)
void Dune::Multiscale::init (int argc, char ** argv)
setup code common to fem/msfem/hmm
References handle_sigterm().
Referenced by main().
std::shared_ptr< CommonTraits::GridType > Dune::Multiscale::make_coarse_grid (const DMP::ProblemContainer & problem, Dune::MPIHelper::MPICommunicator communicator = Dune::MPIHelper::getCommunicator())
References setup().
Referenced by make_grids(), and msfem_algorithm().
template<class T = CommonTraits::DiscreteFunctionType> std::shared_ptr<T> Dune::Multiscale::make_df_ptr (const std::string name, const typename T::SpaceType & space)
std::shared_ptr<CommonTraits::GridType> Dune::Multiscale::make_fine_grid (const DMP::ProblemContainer & problem, std::shared_ptr< CommonTraits::GridType > coarse_gridptr = nullptr, bool check_partitioning = true, Dune::MPIHelper::MPICommunicator communicator = Dune::MPIHelper::getCommunicator())
Referenced by make_grids().
pair< shared_ptr< CommonTraits::GridType >, shared_ptr< CommonTraits::GridType > > Dune::Multiscale::make_grids (const DMP::ProblemContainer & problem, const bool check_partitioning = true, Dune::MPIHelper::MPICommunicator communicator = Dune::MPIHelper::getCommunicator())
abstraction for creating coarse and fine grid instances. shared across msfem/fem codes.
References make_coarse_grid(), and make_fine_grid().
Referenced by main(), and Dune::Multiscale::ErrorCalculator::print().
void Dune::Multiscale::mem_usage ()
Referenced by handle_exception(), and main().
std::map< std::string, double > Dune::Multiscale::msfem_algorithm ()
algorithm
docme
References Dune::Multiscale::Elliptic_MsFEM_Solver::apply(), Dune::Multiscale::Problem::ProblemContainer::config(), Dune::Multiscale::Problem::ProblemContainer::getMutableModelData(), make_coarse_grid(), Dune::Multiscale::Problem::IModelProblemData::prepare_new_evaluation(), Dune::Multiscale::ErrorCalculator::print(), problem(), Dune::Multiscale::CommonTraits::st_gdt_grid_level, and Dune::Multiscale::CommonTraits::world_dim.
Referenced by main().
template<class FunctionType > void Dune::Multiscale::output_all (std::vector< std::unique_ptr< FunctionType >> & functions, CommonTraits::GridViewType & view, std::string name)
Referenced by partition_vis_single(), and subgrid_vis().
void Dune::Multiscale::partition_vis (CommonTraits::GridType & coarse_grid, CommonTraits::GridType & fine_grid)
References partition_vis_single().
void Dune::Multiscale::partition_vis_single (CommonTraits::GridType & grid, std::string function_name)
References output_all().
Referenced by partition_vis().
void Dune::Multiscale::print_info (const Problem::ProblemContainer & problem, std::ostream & out)
outputs Problem info to output stream
References Dune::Multiscale::Problem::ProblemContainer::config(), Dune::Multiscale::Problem::ProblemContainer::getModelData(), Dune::Multiscale::Problem::IModelProblemData::hasExactSolution(), Dune::Multiscale::Problem::IModelProblemData::linear(), and Dune::Multiscale::Problem::ProblemContainer::name().
void Dune::Multiscale::subgrid_vis (DMP::ProblemContainer & problem, CommonTraits::GridType & coarse_grid, CommonTraits::GridType & fine_grid)
References Dune::Multiscale::LocalGridList::covers_strict(), id_to_ulong(), output_all(), Dune::Multiscale::LocalGridList::size(), and Dune::Multiscale::CommonTraits::st_gdt_grid_level.
void Dune::Multiscale::write_discrete_function (const DMP::ProblemContainer & problem, typename CommonTraits::DiscreteFunction_ptr & discrete_solution, const std::string prefix)
write discrete function VTK Output
References Dune::Multiscale::Problem::ProblemContainer::config(), Dune::Multiscale::Problem::ProblemContainer::getExactSolution(), Dune::Multiscale::Problem::ProblemContainer::getModelData(), Dune::Multiscale::Problem::IModelProblemData::hasExactSolution(), and Dune::Multiscale::OutputParameters::set_prefix().
void Dune::Multiscale::write_discrete_function (CommonTraits::DiscreteFunctionType & discrete_solution, const std::string prefix)