Dune::Multiscale::Problem::Random::Diffusion Class Reference
Dune::Multiscale::Problem::Random::Diffusion Class Reference abstract
#include <dune/multiscale/problems/random.hh>
Public Member Functions
Diffusion ()
virtual void evaluate (const DomainType &x, DiffusionBase::RangeType &y) const finaloverride
currently used in gdt assembler
PURE HOT void diffusiveFlux (const DomainType &x, const Problem::JacobianRangeType &direction, Problem::JacobianRangeType &flux) const finaloverride
virtual size_t order () const finaloverride
virtual void init (const DMP::ProblemContainer &problem, MPIHelper::MPICommunicator global, MPIHelper::MPICommunicator local) finaloverride
call this once per grid setup
virtual void prepare_new_evaluation () finaloverride
call this once per "run"
virtual void evaluate (const DomainType &x, CommonTraits::DiffusionFunctionBaseType::RangeType &y) const =0
currently used in gdt assembler
virtual void jacobianDiffusiveFlux (const DomainType &x, const Problem::JacobianRangeType &, const Problem::JacobianRangeType &direction_gradient, Problem::JacobianRangeType &flux) const
Constructor & Destructor Documentation
Dune::Multiscale::Problem::Random::Diffusion::Diffusion ()
Member Function Documentation
PURE HOT void Dune::Multiscale::Problem::Random::Diffusion::diffusiveFlux (const DomainType & x, const Problem::JacobianRangeType & direction, Problem::JacobianRangeType & flux) const final override virtual
in the linear setting, use the structure A^{}_i(x,) = A^{}_{i1}(x) + A^{}_{i2}(x) (diffusive) flux = A^{}(x , direction) (typically direction is some 'gradient_of_a_function')
Implements Dune::Multiscale::Problem::DiffusionBase.
References evaluate(), and Dune::Multiscale::CommonTraits::world_dim.
virtual void Dune::Multiscale::Problem::Random::Diffusion::evaluate (const DomainType & x, DiffusionBase::RangeType & y) const final override virtual
currently used in gdt assembler
Referenced by diffusiveFlux().
void Dune::Multiscale::Problem::Random::Diffusion::init (const DMP::ProblemContainer & , MPIHelper::MPICommunicator , MPIHelper::MPICommunicator) final override virtual
call this once per grid setup
Reimplemented from Dune::Multiscale::Problem::DiffusionBase.
References Dune::Multiscale::Problem::ProblemContainer::config().
size_t Dune::Multiscale::Problem::Random::Diffusion::order () const final override virtual
Reimplemented from Dune::Multiscale::Problem::DiffusionBase.
void Dune::Multiscale::Problem::Random::Diffusion::prepare_new_evaluation () final override virtual
call this once per "run"
Reimplemented from Dune::Multiscale::Problem::DiffusionBase.
The documentation for this class was generated from the following files:
random.hh
random.cc