Dune::Multiscale::OutputParameters Struct Reference
Dune::Multiscale::OutputParameters Struct Reference
define output parameters for Dune::DataOutput
#include <dune/multiscale/tools/misc/outputparameter.hh>
Public Member Functions
OutputParameters (const std::string _path)
virtual ~OutputParameters ()
void set_prefix (std::string my_prefix)
std::string path () const
path where the data is stored
std::string fullpath (const std::string function)
Detailed Description
define output parameters for Dune::DataOutput
Constructor & Destructor Documentation
Dune::Multiscale::OutputParameters::OutputParameters (const std::string _path) explicit
virtual Dune::Multiscale::OutputParameters::~OutputParameters () inline virtual
Member Function Documentation
std::string Dune::Multiscale::OutputParameters::fullpath (const std::string function)
References path().
std::string Dune::Multiscale::OutputParameters::path () const
path where the data is stored
Referenced by fullpath().
void Dune::Multiscale::OutputParameters::set_prefix (std::string my_prefix)
Referenced by Dune::Multiscale::cgfem_algorithm(), solution_output(), and Dune::Multiscale::write_discrete_function().
The documentation for this struct was generated from the following files:
outputparameter.hh
outputparameter.cc