Dune::Multiscale::BoundaryValueHelper< LocalNeumann > Class Template Reference
Dune::Multiscale::BoundaryValueHelper< LocalNeumann > Class Template Reference
holds functionals,etc for boundary correctors to make conditional usage simpler
Public Member Functions
BoundaryValueHelper (const DMP::ProblemContainer &problem, const MsFEMTraits::LocalSpaceType &localSpace, const Problem::LocalDiffusionType &local_diffusion_operator, MsFEMTraits::LocalSolutionVectorType &allLocalRHS, std::size_t coarseBaseFunc)
void dirichlet_projection (const CommonTraits::SpaceType &coarse_space)
void add_to (GDT::SystemAssembler< MsFEMTraits::LocalSpaceType > &system_assembler)
Detailed Description
template<class LocalNeumann>
class Dune::Multiscale::BoundaryValueHelper< LocalNeumann >
holds functionals,etc for boundary correctors to make conditional usage simpler
Constructor & Destructor Documentation
template<class LocalNeumann > Dune::Multiscale::BoundaryValueHelper< LocalNeumann >::BoundaryValueHelper (const DMP::ProblemContainer & problem, const MsFEMTraits::LocalSpaceType & localSpace, const Problem::LocalDiffusionType & local_diffusion_operator, MsFEMTraits::LocalSolutionVectorType & allLocalRHS, std::size_t coarseBaseFunc) inline
Member Function Documentation
template<class LocalNeumann > void Dune::Multiscale::BoundaryValueHelper< LocalNeumann >::add_to (GDT::SystemAssembler< MsFEMTraits::LocalSpaceType > & system_assembler) inline
template<class LocalNeumann > void Dune::Multiscale::BoundaryValueHelper< LocalNeumann >::dirichlet_projection (const CommonTraits::SpaceType & coarse_space) inline
References Dune::Multiscale::Problem::IModelProblemData::boundaryInfo(), Dune::Multiscale::Problem::ProblemContainer::getDirichletData(), and Dune::Multiscale::Problem::ProblemContainer::getModelData().
The documentation for this class was generated from the following file:
localoperator.cc