Dune::Multiscale::LocalproblemSolutionManager Class Reference
Dune::Multiscale::LocalproblemSolutionManager Class Reference
One LocalSolutionManager instance per coarse cell.
#include <dune/multiscale/msfem/localproblems/localsolutionmanager.hh>
Public Member Functions
LocalproblemSolutionManager (const CommonTraits::SpaceType &coarse_space, const MsFEMTraits::CoarseEntityType &coarseEntity, const LocalGridList &subgridList)
MsFEMTraits::LocalSolutionVectorType & getLocalSolutions ()
const MsFEMTraits::LocalSpaceType & space () const
const
MsFEMTraits::LocalGridViewType & grid_view () const
void load ()
void save () const
std::size_t numBoundaryCorrectors () const
Detailed Description
One LocalSolutionManager instance per coarse cell.
Constructor & Destructor Documentation
Dune::Multiscale::LocalproblemSolutionManager::LocalproblemSolutionManager (const CommonTraits::SpaceType & coarse_space, const MsFEMTraits::CoarseEntityType & coarseEntity, const LocalGridList & subgridList)
References Dune::Multiscale::MemoryBackend::space().
Member Function Documentation
MsFEMTraits::LocalSolutionVectorType & Dune::Multiscale::LocalproblemSolutionManager::getLocalSolutions ()
Referenced by Dune::Multiscale::MsFEMCodim0Integral::apply(), Dune::Multiscale::RhsCodim0Integral::apply(), and Dune::Multiscale::LocalProblemSolver::solve_for_all_cells().
const MsFEMTraits::LocalGridViewType& Dune::Multiscale::LocalproblemSolutionManager::grid_view () const
void Dune::Multiscale::LocalproblemSolutionManager::load ()
References Dune::Multiscale::MemoryBackend::read().
std::size_t Dune::Multiscale::LocalproblemSolutionManager::numBoundaryCorrectors () const
Referenced by Dune::Multiscale::MsFEMCodim0Integral::apply(), and Dune::Multiscale::RhsCodim0Integral::apply().
void Dune::Multiscale::LocalproblemSolutionManager::save () const
References Dune::Multiscale::MemoryBackend::append().
Referenced by Dune::Multiscale::LocalProblemSolver::solve_for_all_cells().
const MsFEMTraits::LocalSpaceType & Dune::Multiscale::LocalproblemSolutionManager::space () const
References Dune::Multiscale::MemoryBackend::space().
The documentation for this class was generated from the following files:
localsolutionmanager.hh
localsolutionmanager.cc