Dune::Multiscale::MsFemCodim0Matrix Class Reference
Dune::Multiscale::MsFemCodim0Matrix Class Reference
#include <dune/multiscale/msfem/coarse_scale_assembler.hh>
Public Types
typedef MsFemCodim0MatrixTraits Traits
typedef Traits::LocalOperatorType LocalOperatorType
Public Member Functions
MsFemCodim0Matrix (const LocalOperatorType &op, LocalGridList &localGridList)
const LocalOperatorType & localOperator () const
std::vector< size_t > numTmpObjectsRequired () const
void assembleLocal (const CommonTraits::SpaceType &testSpace, const CommonTraits::SpaceType &ansatzSpace, const CommonTraits::EntityType &coarse_grid_entity, CommonTraits::LinearOperatorType &systemMatrix, std::vector< std::vector< Dune::DynamicMatrix< CommonTraits::RangeFieldType >>> &tmpLocalMatricesContainer, std::vector< Dune::DynamicVector< size_t >> &tmpIndicesContainer) const
Member Typedef Documentation
typedef Traits::LocalOperatorType Dune::Multiscale::MsFemCodim0Matrix::LocalOperatorType
typedef MsFemCodim0MatrixTraits Dune::Multiscale::MsFemCodim0Matrix::Traits
Constructor & Destructor Documentation
Dune::Multiscale::MsFemCodim0Matrix::MsFemCodim0Matrix (const LocalOperatorType & op, LocalGridList & localGridList)
Member Function Documentation
void Dune::Multiscale::MsFemCodim0Matrix::assembleLocal (const CommonTraits::SpaceType & testSpace, const CommonTraits::SpaceType & ansatzSpace, const CommonTraits::EntityType & coarse_grid_entity, CommonTraits::LinearOperatorType & systemMatrix, std::vector< std::vector< Dune::DynamicMatrix< CommonTraits::RangeFieldType >>> & tmpLocalMatricesContainer, std::vector< Dune::DynamicVector< size_t >> & tmpIndicesContainer) const
References Dune::Multiscale::MsFEMCodim0Integral::apply(), Dune::Multiscale::LocalGridList::covers(), and Dune::Multiscale::MsFEMCodim0Integral::numTmpObjectsRequired().
const MsFemCodim0Matrix::LocalOperatorType & Dune::Multiscale::MsFemCodim0Matrix::localOperator () const
std::vector< size_t > Dune::Multiscale::MsFemCodim0Matrix::numTmpObjectsRequired () const
References Dune::Multiscale::MsFEMCodim0Integral::numTmpObjectsRequired().
The documentation for this class was generated from the following files:
coarse_scale_assembler.hh
coarse_scale_assembler.cc