Dune::Multiscale::ErrorCalculator Class Reference
Dune::Multiscale::ErrorCalculator Class Reference
#include <dune/multiscale/common/error_calc.hh>
Public Member Functions
ErrorCalculator (const Problem::ProblemContainer &problem, const std::unique_ptr< LocalsolutionProxy > &msfem_solution, CommonTraits::ConstDiscreteFunctionType *fem_solution)
ErrorCalculator (const Problem::ProblemContainer &problem, const std::unique_ptr< LocalsolutionProxy > &msfem_solution)
this one runs cg-fem sim if mandated by config
std::map< std::string, double > print (std::ostream &out)
Constructor & Destructor Documentation
Dune::Multiscale::ErrorCalculator::ErrorCalculator (const Problem::ProblemContainer & problem, const std::unique_ptr< LocalsolutionProxy > & msfem_solution, CommonTraits::ConstDiscreteFunctionType * fem_solution)
ErrorCalculator::ErrorCalculator (const Problem::ProblemContainer & problem, const std::unique_ptr< LocalsolutionProxy > & msfem_solution)
this one runs cg-fem sim if mandated by config
References Dune::Multiscale::Problem::ProblemContainer::config(), and problem().
Member Function Documentation
std::map< std::string, double > Dune::Multiscale::ErrorCalculator::print (std::ostream & out)
Compute and print errors between exact, msfem and fem solution
This computes the errors between the exact solution, the msfem solution and the fem solution (if they exist respectively). The results are printed to the given ostream and returned in a std::map.
Parameters
[in] out The ostream for error printing
Returns
Returns the computed errors as std::map with the following entries:
"msfem_exact_L2" The L2 error between the msfem solution and the exact solution
"msfem_exact_H1" The H1 error between the msfem solution and the exact solution
"fem_exact_L2" The L2 error between the fem solution and the exact solution
"fem_exact_H1" The H1 error between the fem solution and the exact solution
"msfem_fem_L2" The L2 error between the msfem solution and the fem solution Here, each entry will only be present if the corresponding error was computed.
--------------— compute L2- and H1- errors ----------------—
References data_output(), Dune::Multiscale::CommonTraits::InteriorPartition, Dune::Multiscale::make_grids(), Dune::Multiscale::SpaceChooser< G, R, r >::make_space(), match_check(), Dune::Multiscale::MsFEMProjection::project(), solution_output(), and Dune::Multiscale::Elliptic_FEM_Solver::solve().
Referenced by Dune::Multiscale::cgfem_algorithm(), and Dune::Multiscale::msfem_algorithm().
The documentation for this class was generated from the following files:
error_calc.hh
error_calc.cc