Dune::Multiscale::LocalProblemDataOutputParameters Struct Reference
Dune::Multiscale::LocalProblemDataOutputParameters Struct Reference
define output parameters for local problems appends "local_problems" for path
Public Member Functions
LocalProblemDataOutputParameters (const Problem::ProblemContainer &problem)
void set_prefix (std::string my_prefix)
std::string path () const
path where the data is stored
std::string fullpath (const std::string function)
Detailed Description
define output parameters for local problems appends "local_problems" for path
Constructor & Destructor Documentation
Dune::Multiscale::LocalProblemDataOutputParameters::LocalProblemDataOutputParameters (const Problem::ProblemContainer & problem) explicit
Member Function Documentation
std::string Dune::Multiscale::OutputParameters::fullpath (const std::string function) inherited
References Dune::Multiscale::OutputParameters::path().
std::string Dune::Multiscale::OutputParameters::path () const inherited
path where the data is stored
Referenced by Dune::Multiscale::OutputParameters::fullpath().
void Dune::Multiscale::OutputParameters::set_prefix (std::string my_prefix) inherited
Referenced by Dune::Multiscale::cgfem_algorithm(), solution_output(), and Dune::Multiscale::write_discrete_function().
The documentation for this struct was generated from the following file:
localproblemsolver.cc