Dune::Multiscale::LocalGridList Class Reference
Dune::Multiscale::LocalGridList Class Reference
container for cell problem subgrids
#include <dune/multiscale/msfem/localproblems/localgridlist.hh>
Public Member Functions
LocalGridList (const Dune::Multiscale::Problem::ProblemContainer &problem, const CommonTraits::SpaceType &coarseSpace)
MsFEMTraits::LocalGridType & getSubGrid (IndexType i)
TODO toggle commnet. only used in ProxyGridView.
const MsFEMTraits::LocalGridType & getSubGrid (IndexType i) const
const MsFEMTraits::LocalGridType & getSubGrid (const MsFEMTraits::CoarseEntityType &entity) const
MsFEMTraits::LocalGridType & getSubGrid (const MsFEMTraits::CoarseEntityType &entity)
std::size_t size () const
bool covers (const MsFEMTraits::CoarseEntityType &coarse_entity, const MsFEMTraits::LocalEntityType &local_entity)
returns true if local_entity's center is inside coarse_entity
Static Public Member Functions
static bool covers_strict (const MsFEMTraits::CoarseEntityType &coarse_entity, const MsFEMTraits::LocalEntityType &local_entity)
returns true iff all corners of local_entity are inside coarse_entity
template<class GridImp , template< int, int, class > class GeometryImp>
static bool covers_strict (const MsFEMTraits::CoarseEntityType &coarse_entity, const Dune::Geometry< CommonTraits::world_dim, CommonTraits::world_dim, GridImp, GeometryImp > &local_geometry)
Detailed Description
container for cell problem subgrids
Constructor & Destructor Documentation
Dune::Multiscale::LocalGridList::LocalGridList (const Dune::Multiscale::Problem::ProblemContainer & problem, const CommonTraits::SpaceType & coarseSpace)
References Dune::Multiscale::Problem::ProblemContainer::config(), Dune::Multiscale::Problem::ProblemContainer::getModelData(), and Dune::Multiscale::Problem::IModelProblemData::gridCorners().
Member Function Documentation
bool Dune::Multiscale::LocalGridList::covers (const MsFEMTraits::CoarseEntityType & coarse_entity, const MsFEMTraits::LocalEntityType & local_entity)
returns true if local_entity's center is inside coarse_entity
Referenced by Dune::Multiscale::MsFemCodim0Matrix::assembleLocal(), and Dune::Multiscale::RhsCodim0Vector::assembleLocal().
bool Dune::Multiscale::LocalGridList::covers_strict (const MsFEMTraits::CoarseEntityType & coarse_entity, const MsFEMTraits::LocalEntityType & local_entity) static
returns true iff all corners of local_entity are inside coarse_entity
Referenced by Dune::Multiscale::subgrid_vis().
template<class GridImp , template< int, int, class > class GeometryImp> bool Dune::Multiscale::LocalGridList::covers_strict (const MsFEMTraits::CoarseEntityType & coarse_entity, const Dune::Geometry< CommonTraits::world_dim, CommonTraits::world_dim, GridImp, GeometryImp > & local_geometry) static
MsFEMTraits::LocalGridType & Dune::Multiscale::LocalGridList::getSubGrid (IndexType i)
TODO toggle commnet. only used in ProxyGridView.
Referenced by getSubGrid(), and Dune::Multiscale::LocalGridSearch::operator()().
const MsFEMTraits::LocalGridType & Dune::Multiscale::LocalGridList::getSubGrid (IndexType i) const
const MsFEMTraits::LocalGridType & Dune::Multiscale::LocalGridList::getSubGrid (const MsFEMTraits::CoarseEntityType & entity) const
Get the subgrid belonging to a given coarse cell.
Parameters
[in] coarseCell The coarse cell.
Returns
Returns the subgrid belonging to the given coarse cell.
References getSubGrid().
MsFEMTraits::LocalGridType & Dune::Multiscale::LocalGridList::getSubGrid (const MsFEMTraits::CoarseEntityType & entity)
References getSubGrid().
std::size_t Dune::Multiscale::LocalGridList::size () const
Referenced by Dune::Multiscale::ProxyGridview::ProxyGridview(), and Dune::Multiscale::subgrid_vis().
The documentation for this class was generated from the following files:
localgridlist.hh
localgridlist.cc