Dune::Multiscale::RhsCodim0Vector Class Reference
Dune::Multiscale::RhsCodim0Vector Class Reference
#include <dune/multiscale/msfem/coarse_rhs_functional.hh>
Public Types
typedef RhsCodim0VectorTraits Traits
Public Member Functions
RhsCodim0Vector (const RhsCodim0Integral &func, LocalGridList &localGridList)
const RhsCodim0Integral & localFunctional () const
std::vector< size_t > numTmpObjectsRequired () const
void assembleLocal (const CommonTraits::SpaceType &testSpace, const CommonTraits::EntityType &coarse_grid_entity, CommonTraits::GdtVectorType &systemVector, std::vector< std::vector< Dune::DynamicVector< CommonTraits::RangeFieldType >>> &tmpLocalVectorContainer, Dune::DynamicVector< size_t > &tmpIndices) const
Member Typedef Documentation
typedef RhsCodim0VectorTraits Dune::Multiscale::RhsCodim0Vector::Traits
Constructor & Destructor Documentation
Dune::Multiscale::RhsCodim0Vector::RhsCodim0Vector (const RhsCodim0Integral & func, LocalGridList & localGridList) inline
Member Function Documentation
void Dune::Multiscale::RhsCodim0Vector::assembleLocal (const CommonTraits::SpaceType & testSpace, const CommonTraits::EntityType & coarse_grid_entity, CommonTraits::GdtVectorType & systemVector, std::vector< std::vector< Dune::DynamicVector< CommonTraits::RangeFieldType >>> & tmpLocalVectorContainer, Dune::DynamicVector< size_t > & tmpIndices) const
Todo:
fill with actual values
References Dune::Multiscale::RhsCodim0Integral::apply(), Dune::Multiscale::LocalGridList::covers(), and Dune::Multiscale::RhsCodim0Integral::numTmpObjectsRequired().
const RhsCodim0Integral& Dune::Multiscale::RhsCodim0Vector::localFunctional () const inline
std::vector< size_t > Dune::Multiscale::RhsCodim0Vector::numTmpObjectsRequired () const
References Dune::Multiscale::RhsCodim0Integral::numTmpObjectsRequired().
The documentation for this class was generated from the following files:
coarse_rhs_functional.hh
coarse_rhs_functional.cc