Dune::Multiscale::Elliptic_MsFEM_Solver Class Reference
Dune::Multiscale::Elliptic_MsFEM_Solver Class Reference
needs a better name
#include <dune/multiscale/msfem/msfem_solver.hh>
Public Member Functions
void apply (Problem::ProblemContainer &problem, const CommonTraits::SpaceType &coarse_space, std::unique_ptr< LocalsolutionProxy > &msfem_solution, LocalGridList &localgrid_list) const
Detailed Description
needs a better name
Member Function Documentation
void Dune::Multiscale::Elliptic_MsFEM_Solver::apply (Problem::ProblemContainer & problem, const CommonTraits::SpaceType & coarse_space, std::unique_ptr< LocalsolutionProxy > & msfem_solution, LocalGridList & localgrid_list) const
∇ (A(x,∇u)) + b ∇u + c u = f - divG then: A –> diffusion operator ('DiffusionOperatorType') b –> advective part ('AdvectionTermType') c –> reaction part ('ReactionTermType') f –> 'first' source term, scalar ('SourceTermType') homogenous Dirchilet boundary condition!:
Solutions are kept in-memory via DiscreteFunctionIO::MemoryBackend by LocalsolutionManagers
identify fine scale part of MsFEM solution (including the projection!)
References Dune::Multiscale::CoarseScaleOperator::apply_inverse(), Dune::Multiscale::DiscreteFunctionIO::clear_guard(), and Dune::Multiscale::LocalProblemSolver::solve_for_all_cells().
Referenced by Dune::Multiscale::msfem_algorithm().
The documentation for this class was generated from the following files:
msfem_solver.hh
msfem_solver.cc