Dune::Multiscale::Problem::Random::ModelProblemData Struct Reference
Dune::Multiscale::Problem::Random::ModelProblemData Struct Reference
#include <dune/multiscale/problems/random.hh>
Public Member Functions
virtual bool hasExactSolution () const finaloverride
does the problem implement an exact solution?
ModelProblemData (MPIHelper::MPICommunicator, MPIHelper::MPICommunicator, Dune::XT::Common::Configuration)
const BoundaryInfoType & boundaryInfo () const finaloverride
const SubBoundaryInfoType & subBoundaryInfo () const finaloverride
std::pair
< CommonTraits::DomainType,
CommonTraits::DomainType > gridCorners () const finaloverride
virtual void problem_init (DMP::ProblemContainer &problem, MPIHelper::MPICommunicator global, MPIHelper::MPICommunicator local) finaloverride
call this once per grid setup
virtual void prepare_new_evaluation (DMP::ProblemContainer &problem) finaloverride
call this once per "run"
virtual bool symmetricDiffusion () const
is the diffusion matrix symmetric?
virtual bool linear () const
linear/nonlinear toggle
Protected Types
typedef CommonTraits::GridViewType View
typedef
DSG::BoundaryInfoInterface
< typename View::Intersection > BoundaryInfoType
typedef
MsFEMTraits::LocalGridType::LeafGridView SubView
typedef
DSG::BoundaryInfoInterface
< typename
SubView::Intersection > SubBoundaryInfoType
Constructor & Destructor Documentation
Dune::Multiscale::Problem::Random::ModelProblemData::ModelProblemData (MPIHelper::MPICommunicator global, MPIHelper::MPICommunicator local, Dune::XT::Common::Configuration config_in)
Member Function Documentation
const ModelProblemData::BoundaryInfoType & Dune::Multiscale::Problem::Random::ModelProblemData::boundaryInfo () const final override virtual
Implements Dune::Multiscale::Problem::IModelProblemData.
std::pair< CommonTraits::DomainType, CommonTraits::DomainType > Dune::Multiscale::Problem::Random::ModelProblemData::gridCorners () const final override virtual
Reimplemented from Dune::Multiscale::Problem::IModelProblemData.
virtual bool Dune::Multiscale::Problem::Random::ModelProblemData::hasExactSolution () const inline final override virtual
does the problem implement an exact solution?
Reimplemented from Dune::Multiscale::Problem::IModelProblemData.
void Dune::Multiscale::Problem::Random::ModelProblemData::prepare_new_evaluation (DMP::ProblemContainer &) final override virtual
call this once per "run"
Reimplemented from Dune::Multiscale::Problem::IModelProblemData.
References Dune::Multiscale::Problem::ProblemContainer::getMutableDiffusion(), and Dune::Multiscale::Problem::DiffusionBase::prepare_new_evaluation().
void Dune::Multiscale::Problem::Random::ModelProblemData::problem_init (DMP::ProblemContainer & , MPIHelper::MPICommunicator , MPIHelper::MPICommunicator) final override virtual
call this once per grid setup
Reimplemented from Dune::Multiscale::Problem::IModelProblemData.
References Dune::Multiscale::Problem::ProblemContainer::getMutableDiffusion(), and Dune::Multiscale::Problem::DiffusionBase::init().
const ModelProblemData::SubBoundaryInfoType & Dune::Multiscale::Problem::Random::ModelProblemData::subBoundaryInfo () const final override virtual
Implements Dune::Multiscale::Problem::IModelProblemData.
The documentation for this struct was generated from the following files:
random.hh
random.cc