Dune::Multiscale::MsFEMCodim0Integral Class Reference
Dune::Multiscale::MsFEMCodim0Integral Class Reference
#include <dune/multiscale/msfem/coarse_scale_assembler.hh>
Public Types
typedef MsFEMCodim0IntegralTraits Traits
Public Member Functions
MsFEMCodim0Integral (const DMP::DiffusionBase &diffusion, const size_t over_integrate=0)
size_t numTmpObjectsRequired () const
void apply (Multiscale::LocalSolutionManager &localSolutionManager, const MsFEMTraits::LocalEntityType &localGridEntity, const TestLocalfunctionSetInterfaceType &testBase, const AnsatzLocalfunctionSetInterfaceType &ansatzBase, Dune::DynamicMatrix< CommonTraits::RangeFieldType > &ret, std::vector< Dune::DynamicMatrix< CommonTraits::RangeFieldType >> &tmpLocalMatrices) const
Member Typedef Documentation
typedef MsFEMCodim0IntegralTraits Dune::Multiscale::MsFEMCodim0Integral::Traits
Constructor & Destructor Documentation
Dune::Multiscale::MsFEMCodim0Integral::MsFEMCodim0Integral (const DMP::DiffusionBase & diffusion, const size_t over_integrate = 0) explicit
Member Function Documentation
void Dune::Multiscale::MsFEMCodim0Integral::apply (Multiscale::LocalSolutionManager & localSolutionManager, const MsFEMTraits::LocalEntityType & localGridEntity, const TestLocalfunctionSetInterfaceType & testBase, const AnsatzLocalfunctionSetInterfaceType & ansatzBase, Dune::DynamicMatrix< CommonTraits::RangeFieldType > & ret, std::vector< Dune::DynamicMatrix< CommonTraits::RangeFieldType >> & tmpLocalMatrices) const
TODO check indexing. Correct wrt pre-gdt, but still
References Dune::Multiscale::LocalSolutionManager::getLocalSolutions(), Dune::Multiscale::LocalSolutionManager::numBoundaryCorrectors(), and Dune::Multiscale::Problem::DiffusionBase::order().
Referenced by Dune::Multiscale::MsFemCodim0Matrix::assembleLocal().
size_t Dune::Multiscale::MsFEMCodim0Integral::numTmpObjectsRequired () const
Referenced by Dune::Multiscale::MsFemCodim0Matrix::assembleLocal(), and Dune::Multiscale::MsFemCodim0Matrix::numTmpObjectsRequired().
The documentation for this class was generated from the following files:
coarse_scale_assembler.hh
coarse_scale_assembler.cc