Dune::Multiscale::CoarseScaleOperator Class Reference
Dune::Multiscale::CoarseScaleOperator Class Reference
#include <dune/multiscale/msfem/coarse_scale_operator.hh>
Public Types
typedef CoarseScaleOperatorTraits Traits
typedef Traits::MatrixType MatrixType
typedef Traits::SourceSpaceType SourceSpaceType
typedef Traits::RangeSpaceType RangeSpaceType
typedef Traits::GridViewType GridViewType
Public Member Functions
CoarseScaleOperator (const DMP::ProblemContainer &problem, const SourceSpaceType &source_space_in, LocalGridList &localGridList)
virtual ~CoarseScaleOperator ()
virtual void assemble () overridefinal
void apply_inverse (CoarseScaleOperator::CoarseDiscreteFunction &solution)
Static Public Member Functions
static
Stuff::LA::SparsityPatternDefault pattern (const RangeSpaceType &range_space, const SourceSpaceType &source_space, const GridViewType &grid_view)
Member Typedef Documentation
typedef Traits::GridViewType Dune::Multiscale::CoarseScaleOperator::GridViewType
typedef Traits::MatrixType Dune::Multiscale::CoarseScaleOperator::MatrixType
typedef Traits::RangeSpaceType Dune::Multiscale::CoarseScaleOperator::RangeSpaceType
typedef Traits::SourceSpaceType Dune::Multiscale::CoarseScaleOperator::SourceSpaceType
typedef CoarseScaleOperatorTraits Dune::Multiscale::CoarseScaleOperator::Traits
Constructor & Destructor Documentation
Dune::Multiscale::CoarseScaleOperator::CoarseScaleOperator (const DMP::ProblemContainer & problem, const SourceSpaceType & source_space_in, LocalGridList & localGridList)
References Dune::Multiscale::Problem::IModelProblemData::boundaryInfo(), Dune::Multiscale::Problem::ProblemContainer::config(), Dune::Multiscale::Problem::ProblemContainer::getDirichletData(), Dune::Multiscale::Problem::ProblemContainer::getModelData(), Dune::Multiscale::Problem::ProblemContainer::getNeumannData(), and Dune::Multiscale::CommonTraits::InteriorPartition.
virtual Dune::Multiscale::CoarseScaleOperator::~CoarseScaleOperator () inline virtual
Member Function Documentation
void Dune::Multiscale::CoarseScaleOperator::apply_inverse (CoarseScaleOperator::CoarseDiscreteFunction & solution)
References Dune::Multiscale::Problem::ProblemContainer::config(), and Dune::Multiscale::CommonTraits::world_dim.
Referenced by Dune::Multiscale::Elliptic_MsFEM_Solver::apply().
void Dune::Multiscale::CoarseScaleOperator::assemble () final override virtual
Stuff::LA::SparsityPatternDefault Dune::Multiscale::CoarseScaleOperator::pattern (const RangeSpaceType & range_space, const SourceSpaceType & source_space, const GridViewType & grid_view) static
The documentation for this class was generated from the following files:
coarse_scale_operator.hh
coarse_scale_operator.cc