Dune::Multiscale::MemoryBackend Class Reference
Dune::Multiscale::MemoryBackend Class Reference
simple discrete function to disk writer this class isn't type safe in the sense that different appends may append non-convertible discrete function implementations
#include <dune/multiscale/common/df_io.hh>
Public Member Functions
MemoryBackend (IOTraits::GridViewType &grid_view, const std::string="nonsense_default_for_map")
DiscreteFunctionWriter.
void append (const IOTraits::DiscreteFunction_ptr &df)
void read (const unsigned long index, IOTraits::DiscreteFunction_ptr &df)
IOTraits::DiscreteFunctionSpaceType & space ()
Detailed Description
simple discrete function to disk writer this class isn't type safe in the sense that different appends may append non-convertible discrete function implementations
Constructor & Destructor Documentation
Dune::Multiscale::MemoryBackend::MemoryBackend (IOTraits::GridViewType & grid_view, const std::string = "nonsense_default_for_map") inline
DiscreteFunctionWriter.
Parameters
filename will open fstream at config["global.datadir"]/filename filename may include additional path components
Exceptions
Dune::IOError if config["global.datadir"]/filename cannot be opened
Member Function Documentation
void Dune::Multiscale::MemoryBackend::append (const IOTraits::DiscreteFunction_ptr & df) inline
Referenced by Dune::Multiscale::LocalSolutionManager::save().
void Dune::Multiscale::MemoryBackend::read (const unsigned long index, IOTraits::DiscreteFunction_ptr & df) inline
Referenced by Dune::Multiscale::LocalSolutionManager::load().
IOTraits::DiscreteFunctionSpaceType& Dune::Multiscale::MemoryBackend::space () inline
Referenced by Dune::Multiscale::LocalSolutionManager::LocalSolutionManager(), and Dune::Multiscale::LocalSolutionManager::space().
The documentation for this class was generated from the following file:
df_io.hh