Dune::Multiscale::MsFEMProjection Class Reference
Dune::Multiscale::MsFEMProjection Class Reference
#include <dune/multiscale/common/heterogenous.hh>
Static Public Member Functions
static void project (LocalsolutionProxy &source, CommonTraits::DiscreteFunctionType &target)
signature for non-default SearchStrategy constructions
Static Protected Member Functions
static void preprocess (CommonTraits::DiscreteFunctionType &func)
static void postprocess (CommonTraits::DiscreteFunctionType &func)
static void identifySharedNodes (const CommonTraits::GridViewType &gridPart, std::vector< int > &map)
Member Function Documentation
void Dune::Multiscale::MsFEMProjection::identifySharedNodes (const CommonTraits::GridViewType & gridPart, std::vector< int > & map) static protected
void Dune::Multiscale::MsFEMProjection::postprocess (CommonTraits::DiscreteFunctionType & func) static protected
References Dune::Multiscale::CommonTraits::world_dim.
Referenced by project().
void Dune::Multiscale::MsFEMProjection::preprocess (CommonTraits::DiscreteFunctionType & func) static protected
Referenced by project().
void Dune::Multiscale::MsFEMProjection::project (LocalsolutionProxy & source, CommonTraits::DiscreteFunctionType & target) static
signature for non-default SearchStrategy constructions
References Dune::Multiscale::CommonTraits::dimRange, Dune::Multiscale::global_evaluation_points(), Dune::Multiscale::LocalsolutionProxy::local_function(), postprocess(), preprocess(), and Dune::Multiscale::LocalsolutionProxy::search().
Referenced by Dune::Multiscale::ErrorCalculator::print().
The documentation for this class was generated from the following files:
heterogenous.hh
heterogenous.cc