Dune::Multiscale::Problem::ProblemContainer Struct Reference
Dune::Multiscale::Problem::ProblemContainer Struct Reference
#include <dune/multiscale/problems/selector.hh>
Public Types
typedef std::unique_ptr< const
CommonTraits::FunctionBaseType > BasePtr
Public Member Functions
ProblemContainer (MPIHelper::MPICommunicator global, MPIHelper::MPICommunicator local, Dune::XT::Common::Configuration config_in)
const
CommonTraits::FunctionBaseType & getSource () const
const
CommonTraits::FunctionBaseType & getExactSolution () const
const DiffusionBase & getDiffusion () const
DiffusionBase & getMutableDiffusion ()
const IModelProblemData & getModelData () const
IModelProblemData & getMutableModelData ()
const DirichletDataBase & getDirichletData () const
const NeumannDataBase & getNeumannData () const
const std::string name () const
const
Dune::XT::Common::Configuration & config () const
Dune::XT::Common::Configuration & config ()
Member Typedef Documentation
typedef std::unique_ptr<const CommonTraits::FunctionBaseType> Dune::Multiscale::Problem::ProblemContainer::BasePtr
Constructor & Destructor Documentation
Problem::ProblemContainer::ProblemContainer (MPIHelper::MPICommunicator global, MPIHelper::MPICommunicator local, Dune::XT::Common::Configuration config_in)
References getMutableModelData(), and Dune::Multiscale::Problem::IModelProblemData::problem_init().
Member Function Documentation
const Dune::XT::Common::Configuration& Dune::Multiscale::Problem::ProblemContainer::config () const
Referenced by Dune::Multiscale::LocalProblemOperator::apply_inverse(), Dune::Multiscale::CoarseScaleOperator::apply_inverse(), Dune::Multiscale::LocalProblemOperator::assemble_all_local_rhs(), Dune::Multiscale::cgfem_algorithm(), Dune::Multiscale::CoarseScaleOperator::CoarseScaleOperator(), data_output(), Dune::Multiscale::ErrorCalculator::ErrorCalculator(), Dune::Multiscale::Problem::Random::Diffusion::init(), Dune::Multiscale::LocalGridList::LocalGridList(), main(), Dune::Multiscale::msfem_algorithm(), Dune::Multiscale::print_info(), setup(), solution_output(), and Dune::Multiscale::write_discrete_function().
Dune::XT::Common::Configuration & Problem::ProblemContainer::config ()
const Problem::DiffusionBase & Dune::Multiscale::Problem::ProblemContainer::getDiffusion () const
Referenced by Dune::Multiscale::RhsCodim0Integral::apply(), Dune::Multiscale::LocalProblemOperator::assemble_all_local_rhs(), and main().
const Problem::DirichletDataBase & Dune::Multiscale::Problem::ProblemContainer::getDirichletData () const
Referenced by Dune::Multiscale::CoarseScaleOperator::CoarseScaleOperator(), and Dune::Multiscale::BoundaryValueHelper< LocalNeumann >::dirichlet_projection().
const CommonTraits::FunctionBaseType & Dune::Multiscale::Problem::ProblemContainer::getExactSolution () const
Referenced by data_output(), and Dune::Multiscale::write_discrete_function().
const Problem::IModelProblemData & Dune::Multiscale::Problem::ProblemContainer::getModelData () const
Referenced by Dune::Multiscale::CoarseScaleOperator::CoarseScaleOperator(), data_output(), Dune::Multiscale::BoundaryValueHelper< LocalNeumann >::dirichlet_projection(), Dune::Multiscale::LocalGridList::LocalGridList(), Dune::Multiscale::print_info(), setup(), and Dune::Multiscale::write_discrete_function().
Problem::DiffusionBase & Dune::Multiscale::Problem::ProblemContainer::getMutableDiffusion ()
Referenced by Dune::Multiscale::Problem::Random::ModelProblemData::prepare_new_evaluation(), and Dune::Multiscale::Problem::Random::ModelProblemData::problem_init().
Problem::IModelProblemData & Dune::Multiscale::Problem::ProblemContainer::getMutableModelData ()
Referenced by Dune::Multiscale::cgfem_algorithm(), main(), Dune::Multiscale::msfem_algorithm(), and ProblemContainer().
const Problem::NeumannDataBase & Dune::Multiscale::Problem::ProblemContainer::getNeumannData () const
Referenced by Dune::Multiscale::LocalProblemOperator::assemble_all_local_rhs(), and Dune::Multiscale::CoarseScaleOperator::CoarseScaleOperator().
const CommonTraits::FunctionBaseType & Dune::Multiscale::Problem::ProblemContainer::getSource () const
Referenced by Dune::Multiscale::RhsCodim0Integral::apply().
const std::string Dune::Multiscale::Problem::ProblemContainer::name () const
Referenced by Dune::Multiscale::print_info().
The documentation for this struct was generated from the following files:
selector.hh
selector.cc