Dune::Multiscale::LocalGridSearch Class Reference
Dune::Multiscale::LocalGridSearch Class Reference
given a Localgridlist, facilitate searching for evaluation points in a pseudo-hierachical manner
#include <dune/multiscale/msfem/localproblems/localgridsearch.hh>
Public Types
typedef BaseType::EntityVectorType EntityVectorType
Public Member Functions
LocalGridSearch (const CommonTraits::SpaceType &space, const LocalGridList &gridlist)
LocalGridSearch (const LocalGridSearch &other)
EntityVectorType operator() (const PointContainerType &points)
const
MsFEMTraits::CoarseEntityType & current_coarse_pointer () const
bool covers_strict (const CommonTraits::SpaceType::EntityType &coarse_entity, const PointIterator first, const PointIterator last)
Detailed Description
given a Localgridlist, facilitate searching for evaluation points in a pseudo-hierachical manner
Member Typedef Documentation
typedef BaseType::EntityVectorType Dune::Multiscale::LocalGridSearch::EntityVectorType
Constructor & Destructor Documentation
Dune::Multiscale::LocalGridSearch::LocalGridSearch (const CommonTraits::SpaceType & space, const LocalGridList & gridlist)
Dune::Multiscale::LocalGridSearch::LocalGridSearch (const LocalGridSearch & other)
Member Function Documentation
bool Dune::Multiscale::LocalGridSearch::covers_strict (const CommonTraits::SpaceType::EntityType & coarse_entity, const PointIterator first, const PointIterator last)
Referenced by operator()().
const Dune::Multiscale::MsFEMTraits::CoarseEntityType & Dune::Multiscale::LocalGridSearch::current_coarse_pointer () const
Dune::Multiscale::LocalGridSearch::EntityVectorType Dune::Multiscale::LocalGridSearch::operator() (const PointContainerType & points)
References covers_strict(), and Dune::Multiscale::LocalGridList::getSubGrid().
The documentation for this class was generated from the following files:
localgridsearch.hh
localgridsearch.cc