Dune::Multiscale::RhsCodim0Integral Class Reference
Dune::Multiscale::RhsCodim0Integral Class Reference
#include <dune/multiscale/msfem/coarse_rhs_functional.hh>
Public Types
typedef RhsCodim0IntegralTraits Traits
Public Member Functions
RhsCodim0Integral (const DMP::ProblemContainer &problem, const size_t over_integrate=0)
size_t numTmpObjectsRequired () const
void apply (MsFEMTraits::LocalGridDiscreteFunctionType &dirichletExtension, Multiscale::LocalSolutionManager &localSolutionManager, const MsFEMTraits::LocalEntityType &localGridEntity, const TestLocalfunctionSetInterfaceType &testBase, Dune::DynamicVector< CommonTraits::RangeFieldType > &ret, std::vector< Dune::DynamicVector< CommonTraits::RangeFieldType >> &tmpLocalVectors) const
Member Typedef Documentation
typedef RhsCodim0IntegralTraits Dune::Multiscale::RhsCodim0Integral::Traits
Constructor & Destructor Documentation
Dune::Multiscale::RhsCodim0Integral::RhsCodim0Integral (const DMP::ProblemContainer & problem, const size_t over_integrate = 0) inline explicit
Member Function Documentation
void Dune::Multiscale::RhsCodim0Integral::apply (MsFEMTraits::LocalGridDiscreteFunctionType & dirichletExtension, Multiscale::LocalSolutionManager & localSolutionManager, const MsFEMTraits::LocalEntityType & localGridEntity, const TestLocalfunctionSetInterfaceType & testBase, Dune::DynamicVector< CommonTraits::RangeFieldType > & ret, std::vector< Dune::DynamicVector< CommonTraits::RangeFieldType >> & tmpLocalVectors) const
Attention
At this point we assume, that the quadrature points on the subgrid and hostgrid are the same (dirichletExtensionLF is a localfunction on the hostgrid, quadPoint stems from a quadrature on the subgrid)!!
References Dune::Multiscale::Problem::ProblemContainer::getDiffusion(), Dune::Multiscale::LocalSolutionManager::getLocalSolutions(), Dune::Multiscale::Problem::ProblemContainer::getSource(), Dune::Multiscale::LocalSolutionManager::numBoundaryCorrectors(), and Dune::Multiscale::Problem::DiffusionBase::order().
Referenced by Dune::Multiscale::RhsCodim0Vector::assembleLocal().
size_t Dune::Multiscale::RhsCodim0Integral::numTmpObjectsRequired () const
Referenced by Dune::Multiscale::RhsCodim0Vector::assembleLocal(), and Dune::Multiscale::RhsCodim0Vector::numTmpObjectsRequired().
The documentation for this class was generated from the following files:
coarse_rhs_functional.hh
coarse_rhs_functional.cc