grid_creation.cc File Reference
grid_creation.cc File Reference
#include <config.h>
#include "grid_creation.hh"
#include <dune/grid/common/gridenums.hh>
#include <dune/xt/common/ranges.hh>
#include <dune/xt/common/float_cmp.hh>
#include <dune/stuff/grid/structuredgridfactory.hh>
#include <dune/stuff/grid/information.hh>
#include <dune/multiscale/problems/selector.hh>
#include <dune/common/parallel/mpihelper.hh>
#include <dune/multiscale/common/mygridfactory.hh>
Typedefs
typedef tuple
< CommonTraits::DomainType,
CommonTraits::DomainType,
array< unsigned int,
CommonTraits::world_dim >
, array< unsigned int,
CommonTraits::world_dim >
, array< unsigned int,
CommonTraits::world_dim > > SetupReturnType
Functions
SetupReturnType setup (const DMP::ProblemContainer &problem)
template<class T >
std::ostream & operator<< (std::ostream &s, const Dune::Stuff::Common::MinMaxAvg< T > &d)
Typedef Documentation
typedef tuple<CommonTraits::DomainType, CommonTraits::DomainType, array<unsigned int, CommonTraits::world_dim>, array<unsigned int, CommonTraits::world_dim>, array<unsigned int, CommonTraits::world_dim> > SetupReturnType
Function Documentation
template<class T > std::ostream& operator<< (std::ostream & s, const Dune::Stuff::Common::MinMaxAvg< T > & d) inline
SetupReturnType setup (const DMP::ProblemContainer & problem)
References Dune::Multiscale::Problem::ProblemContainer::config(), Dune::Multiscale::Problem::ProblemContainer::getModelData(), Dune::Multiscale::Problem::IModelProblemData::gridCorners(), and Dune::Multiscale::CommonTraits::world_dim.
Referenced by Dune::Multiscale::make_coarse_grid().