cgfem.cc File Reference
cgfem.cc File Reference
#include <config.h>
#include <dune/multiscale/common/main_init.hh>
#include <dune/multiscale/fem/algorithm.hh>
#include <dune/xt/common/parallel/helper.hh>
#include <dune/xt/common/timings.hh>
#include <dune/xt/common/logging.hh>
#include <thread>
#include <tbb/task_scheduler_init.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References Dune::Multiscale::cgfem_algorithm(), Dune::Multiscale::dump_environment(), Dune::Multiscale::handle_exception(), Dune::Multiscale::init(), and Dune::Multiscale::mem_usage().