thread_vis.cc File Reference
thread_vis.cc File Reference
#include <config.h>
#include <dune/multiscale/common/main_init.hh>
#include <dune/multiscale/common/traits.hh>
#include <dune/multiscale/common/grid_creation.hh>
#include <dune/multiscale/msfem/msfem_traits.hh>
#include <dune/multiscale/problems/selector.hh>
#include <dune/multiscale/msfem/localproblems/localgridlist.hh>
#include <dune/multiscale/tools/misc/outputparameter.hh>
#include <dune/stuff/aliases.hh>
#include <dune/xt/common/ranges.hh>
#include <dune/xt/common/parallel/threadmanager.hh>
#include <dune/stuff/grid/output/entity_visualization.hh>
#include <dune/gdt/spaces/fv/default.hh>
Namespaces
Dune
Dune::Multiscale
Functions
template<class FunctionType >
void Dune::Multiscale::output_all (std::vector< std::unique_ptr< FunctionType >> &functions, CommonTraits::GridViewType &view, std::string name)
void Dune::Multiscale::partition_vis_single (CommonTraits::GridType &grid, std::string function_name)
template<class T >
unsigned long Dune::Multiscale::id_to_ulong (const T &id)
template<int k>
unsigned long Dune::Multiscale::id_to_ulong (const Dune::bigunsignedint< k > &id)
void Dune::Multiscale::subgrid_vis (DMP::ProblemContainer &problem, CommonTraits::GridType &coarse_grid, CommonTraits::GridType &fine_grid)
void Dune::Multiscale::partition_vis (CommonTraits::GridType &coarse_grid, CommonTraits::GridType &fine_grid)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References Dune::Multiscale::Problem::ProblemContainer::config(), Dune::Multiscale::Problem::ProblemContainer::getDiffusion(), Dune::Multiscale::Problem::ProblemContainer::getMutableModelData(), Dune::Multiscale::handle_exception(), Dune::Multiscale::init(), Dune::Multiscale::make_grids(), Dune::Multiscale::Problem::IModelProblemData::prepare_new_evaluation(), problem(), and Dune::Multiscale::CommonTraits::world_dim.