error_calc.cc File Reference
error_calc.cc File Reference
#include <config.h>
#include "error_calc.hh"
#include <assert.h>
#include <boost/filesystem/fstream.hpp>
#include <iostream>
#include <map>
#include <unordered_map>
#include <memory>
#include <string>
#include <utility>
#include <dune/gdt/assembler/system.hh>
#include <dune/gdt/discretefunction/default.hh>
#include <dune/gdt/products/l2.hh>
#include <dune/gdt/products/h1.hh>
#include <dune/gdt/operators/prolongations.hh>
#include <dune/multiscale/common/traits.hh>
#include <dune/multiscale/common/grid_creation.hh>
#include <dune/multiscale/problems/base.hh>
#include <dune/multiscale/msfem/localsolution_proxy.hh>
#include <dune/multiscale/msfem/proxygridview.hh>
#include <dune/multiscale/msfem/fem_solver.hh>
#include <dune/multiscale/problems/selector.hh>
#include <dune/multiscale/tools/misc/outputparameter.hh>
#include <dune/xt/common/parallel/partitioner.hh>
#include <dune/grid/utility/partitioning/seedlist.hh>
#include <dune/xt/common/filesystem.hh>
#include <dune/xt/common/configuration.hh>
#include <dune/multiscale/common/heterogenous.hh>
Typedefs
typedef DSFu::Difference
< Problem::ExactSolutionType,
CommonTraits::ConstDiscreteFunctionType > DifferenceType
typedef DSFu::Difference
< CommonTraits::ConstDiscreteFunctionType,
CommonTraits::ConstDiscreteFunctionType > DiscreteDifferenceType
typedef DGP::L2Localizable
< CommonTraits::InteriorGridViewType,
DifferenceType > L2ErrorAnalytical
typedef DGP::L2Localizable
< CommonTraits::InteriorGridViewType,
DiscreteDifferenceType > L2ErrorDiscrete
typedef DGP::H1SemiLocalizable
< CommonTraits::InteriorGridViewType,
DifferenceType > H1sErrorAnalytical
typedef DGP::H1SemiLocalizable
< CommonTraits::InteriorGridViewType,
DiscreteDifferenceType > H1sErrorDiscrete
typedef DGP::L2Localizable
< CommonTraits::InteriorGridViewType,
CommonTraits::ConstDiscreteFunctionType > DiscreteL2
Functions
void solution_output (const DMP::ProblemContainer &problem, const CommonTraits::ConstDiscreteFunctionType &solution, std::string name="msfem_solution_")
template<typename L , typename R >
void solution_output (const DMP::ProblemContainer &problem, const DSFu::Difference< L, R > &solution, const CommonTraits::GridViewType &view, std::string name)
void data_output (const DMP::ProblemContainer &problem, const CommonTraits::GridViewType &gridPart)
Typedef Documentation
typedef DSFu::Difference<Problem::ExactSolutionType, CommonTraits::ConstDiscreteFunctionType> DifferenceType
typedef DSFu::Difference<CommonTraits::ConstDiscreteFunctionType, CommonTraits::ConstDiscreteFunctionType> DiscreteDifferenceType
typedef DGP::L2Localizable<CommonTraits::InteriorGridViewType, CommonTraits::ConstDiscreteFunctionType> DiscreteL2
typedef DGP::H1SemiLocalizable<CommonTraits::InteriorGridViewType, DifferenceType> H1sErrorAnalytical
typedef DGP::H1SemiLocalizable<CommonTraits::InteriorGridViewType, DiscreteDifferenceType> H1sErrorDiscrete
typedef DGP::L2Localizable<CommonTraits::InteriorGridViewType, DifferenceType> L2ErrorAnalytical
typedef DGP::L2Localizable<CommonTraits::InteriorGridViewType, DiscreteDifferenceType> L2ErrorDiscrete
Function Documentation
void data_output (const DMP::ProblemContainer & problem, const CommonTraits::GridViewType & gridPart)
References Dune::Multiscale::Problem::ProblemContainer::config(), Dune::Multiscale::Problem::ProblemContainer::getExactSolution(), Dune::Multiscale::Problem::ProblemContainer::getModelData(), and Dune::Multiscale::Problem::IModelProblemData::hasExactSolution().
Referenced by Dune::Multiscale::ErrorCalculator::print().
void solution_output (const DMP::ProblemContainer & problem, const CommonTraits::ConstDiscreteFunctionType & solution, std::string name = "msfem_solution_")
References Dune::Multiscale::Problem::ProblemContainer::config(), and Dune::Multiscale::OutputParameters::set_prefix().
Referenced by Dune::Multiscale::ErrorCalculator::print().
template<typename L , typename R > void solution_output (const DMP::ProblemContainer & problem, const DSFu::Difference< L, R > & solution, const CommonTraits::GridViewType & view, std::string name)
References Dune::Multiscale::Problem::ProblemContainer::config(), and Dune::Multiscale::OutputParameters::set_prefix().