fail.cc File Reference
fail.cc File Reference
#include <type_traits>
Classes
struct A
struct B
struct Info< T >
struct ProblemBase
struct Problem
Typedefs
typedef A GridA
typedef B GridB
typedef Info< GridA > AI
typedef Info< GridB > BI
Functions
Problem problem ()
template<class J >
std::enable_if< std::is_same
< GridA, J >::value, bool >
::type is_neu (J &j)
template<class J >
std::enable_if<!std::is_same
< GridA, J >::value, bool >
::type is_neu (J &j)
int main ()
Typedef Documentation
typedef Info<GridA> AI
typedef Info<GridB> BI
typedef A GridA
typedef B GridB
Function Documentation
template<class J > std::enable_if<std::is_same<GridA, J>::value, bool>::type is_neu (J & j)
References Problem::info(), Info< T >::ok(), and problem().
Referenced by main().
template<class J > std::enable_if<!std::is_same<GridA, J>::value, bool>::type is_neu (J & j)
References Info< T >::ok(), problem(), and Problem::subinfo().
int main ()
References is_neu().
Problem problem ()
Referenced by Dune::Multiscale::cgfem_algorithm(), Dune::Multiscale::ErrorCalculator::ErrorCalculator(), is_neu(), main(), and Dune::Multiscale::msfem_algorithm().