Problem
Problem
Classes
class Dune::Multiscale::Problem::IModelProblemData
Typedefs
typedef CommonTraits::GridViewType Dune::Multiscale::Problem::IModelProblemData::View
typedef
DSG::BoundaryInfoInterface
< typename View::Intersection > Dune::Multiscale::Problem::IModelProblemData::BoundaryInfoType
typedef
MsFEMTraits::LocalGridType::LeafGridView Dune::Multiscale::Problem::IModelProblemData::SubView
typedef
DSG::BoundaryInfoInterface
< typename
SubView::Intersection > Dune::Multiscale::Problem::IModelProblemData::SubBoundaryInfoType
Functions
virtual void Dune::Multiscale::Problem::DiffusionBase::evaluate (const DomainType &x, CommonTraits::DiffusionFunctionBaseType::RangeType &y) const =0
currently used in gdt assembler
virtual Dune::Multiscale::Problem::DiffusionBase::~DiffusionBase ()
virtual void Dune::Multiscale::Problem::DiffusionBase::diffusiveFlux (const DomainType &x, const Problem::JacobianRangeType &direction, Problem::JacobianRangeType &flux) const =0
virtual void Dune::Multiscale::Problem::DiffusionBase::jacobianDiffusiveFlux (const DomainType &x, const Problem::JacobianRangeType &, const Problem::JacobianRangeType &direction_gradient, Problem::JacobianRangeType &flux) const
virtual size_t Dune::Multiscale::Problem::DiffusionBase::order () const
virtual void Dune::Multiscale::Problem::DiffusionBase::init (const ProblemContainer &, MPIHelper::MPICommunicator, MPIHelper::MPICommunicator)
call this once per grid setup
virtual void Dune::Multiscale::Problem::DiffusionBase::prepare_new_evaluation ()
call this once per "run"
virtual void Dune::Multiscale::Problem::DirichletDataBase::evaluate (const DomainType &x, RangeType &y) const =0
virtual size_t Dune::Multiscale::Problem::DirichletDataBase::order () const
virtual void Dune::Multiscale::Problem::ZeroDirichletData::evaluate (const DomainType &, RangeType &y) const final
virtual size_t Dune::Multiscale::Problem::ZeroDirichletData::order () const
virtual void Dune::Multiscale::Problem::NeumannDataBase::evaluate (const DomainType &x, RangeType &y) const =0
virtual size_t Dune::Multiscale::Problem::NeumannDataBase::order () const
virtual void Dune::Multiscale::Problem::ZeroNeumannData::evaluate (const DomainType &, RangeType &y) const final
virtual size_t Dune::Multiscale::Problem::ZeroNeumannData::order () const
Dune::Multiscale::Problem::IModelProblemData::IModelProblemData (MPIHelper::MPICommunicator, MPIHelper::MPICommunicator, Dune::XT::Common::Configuration)
Constructor for ModelProblemData.
virtual Dune::Multiscale::Problem::IModelProblemData::~IModelProblemData ()
virtual bool Dune::Multiscale::Problem::IModelProblemData::hasExactSolution () const
does the problem implement an exact solution?
virtual bool Dune::Multiscale::Problem::IModelProblemData::symmetricDiffusion () const
is the diffusion matrix symmetric?
virtual bool Dune::Multiscale::Problem::IModelProblemData::linear () const
linear/nonlinear toggle
virtual const BoundaryInfoType & Dune::Multiscale::Problem::IModelProblemData::boundaryInfo () const =0
virtual const SubBoundaryInfoType & Dune::Multiscale::Problem::IModelProblemData::subBoundaryInfo () const =0
virtual std::pair
< CommonTraits::DomainType,
CommonTraits::DomainType > Dune::Multiscale::Problem::IModelProblemData::gridCorners () const
virtual void Dune::Multiscale::Problem::IModelProblemData::problem_init (DMP::ProblemContainer &, MPIHelper::MPICommunicator, MPIHelper::MPICommunicator)
call this once per grid setup
virtual void Dune::Multiscale::Problem::IModelProblemData::prepare_new_evaluation (DMP::ProblemContainer &)
call this once per "run"
Detailed Description
in general we regard problems of the following type:
div (A^{} (x, u^{})) + m^{} u^{} = f - div G
Here we have: u^{} = exact solution of the problem A^{} = diffusion matrix (or tensor), e.g. with the structure A^{}(x) = A(x,{x}{}) m^{} = a mass term (or reaction term), e.g. with the structure m^{}(x) = m(x,{x}{}) f = first source term with the structure f = f(x) (=> no micro-scale dependency) G = second source term with the structure G = G(x) (=> no micro-scale dependency). (Note that 'G' is directly implemented! We do not implement '- div G'!)
A^{} is can be a monotone operator (=> use HMM, the MsFEM is not implemented for nonlinear problems)
! we use the following class names:
class ExactSolution -> describes u^{} methods: evaluate u^{}(x) –> evaluate evaluate u^{}(x) –> jacobian
class Diffusion -> describes A^{} methods: evaluate A^{}(x , direction) –> diffusiveFlux evaluate DA^{}(x , position) direction –> jacobianDiffusiveFlux
class MassTerm -> describes m^{} methods: evaluate m^{}(x) –> evaluate
class FirstSource -> describes f methods: evaluate f(x) –> evaluate
class SecondSource -> describes G methods: evaluate G(x) –> evaluate
! See 'elliptic_problems/example.hh' for details
The mass (or reaction) term m^{} is given by: ! m^{} := Since tends to zero, we may say that we do not have a real mass term for our problem. It is a simple condition to fix the solution which is only unique up to a constant. In fact we still approximate the solution of the problem without mass.
The first source term f is given by: ! f(x) := **** since the second source is zero, f will form the right hand side (RHS) of our discrete problem
The second source term G is constantly zero: ! G(x) := 0
!FirstSource defines the right hand side (RHS) of the governing problem (i.e. it defines 'f'). The value of the right hand side (i.e. the value of 'f') at 'x' is accessed by the method 'evaluate'. That means 'y := f(x)' and 'y' is returned. It is only important that 'RHSFunction' knows the function space ('FuncSpace') that it is part from. (f FunctionSpace)
Typedef Documentation
typedef DSG::BoundaryInfoInterface<typename View::Intersection> Dune::Multiscale::Problem::IModelProblemData::BoundaryInfoType protected
typedef DSG::BoundaryInfoInterface<typename SubView::Intersection> Dune::Multiscale::Problem::IModelProblemData::SubBoundaryInfoType protected
typedef MsFEMTraits::LocalGridType::LeafGridView Dune::Multiscale::Problem::IModelProblemData::SubView protected
typedef CommonTraits::GridViewType Dune::Multiscale::Problem::IModelProblemData::View protected
Function Documentation
virtual const BoundaryInfoType& Dune::Multiscale::Problem::IModelProblemData::boundaryInfo () const pure virtual
Implemented in Dune::Multiscale::Problem::Random::ModelProblemData, Dune::Multiscale::Problem::Synthetic::ModelProblemData, Dune::Multiscale::Problem::SPE10::ModelProblemData, and Dune::Multiscale::Problem::Tarbert::ModelProblemData.
Referenced by Dune::Multiscale::CoarseScaleOperator::CoarseScaleOperator(), and Dune::Multiscale::BoundaryValueHelper< LocalNeumann >::dirichlet_projection().
virtual void Dune::Multiscale::Problem::DiffusionBase::diffusiveFlux (const DomainType & x, const Problem::JacobianRangeType & direction, Problem::JacobianRangeType & flux) const pure virtual
in the linear setting, use the structure A^{}_i(x,) = A^{}_{i1}(x) + A^{}_{i2}(x) (diffusive) flux = A^{}(x , direction) (typically direction is some 'gradient_of_a_function')
Implemented in Dune::Multiscale::Problem::Random::Diffusion, Dune::Multiscale::Problem::Synthetic::Diffusion, Dune::Multiscale::Problem::SPE10::Diffusion, Dune::Multiscale::Problem::Tarbert::Diffusion, and Dune::Multiscale::Problem::Thirteen::Diffusion.
Referenced by Dune::Multiscale::CoarseBasisProduct::evaluate(), and Dune::Multiscale::DirichletProduct::evaluate().
virtual void Dune::Multiscale::Problem::DiffusionBase::evaluate (const DomainType & x, CommonTraits::DiffusionFunctionBaseType::RangeType & y) const pure virtual
currently used in gdt assembler
virtual void Dune::Multiscale::Problem::DirichletDataBase::evaluate (const DomainType & x, RangeType & y) const pure virtual
Implemented in Dune::Multiscale::Problem::Random::DirichletData, Dune::Multiscale::Problem::Synthetic::DirichletData, and Dune::Multiscale::Problem::ZeroDirichletData.
virtual void Dune::Multiscale::Problem::ZeroDirichletData::evaluate (const DomainType & , RangeType & y) const inline final virtual
Implements Dune::Multiscale::Problem::DirichletDataBase.
virtual void Dune::Multiscale::Problem::NeumannDataBase::evaluate (const DomainType & x, RangeType & y) const pure virtual
Implemented in Dune::Multiscale::Problem::Random::NeumannData, Dune::Multiscale::Problem::Synthetic::NeumannData, and Dune::Multiscale::Problem::ZeroNeumannData.
virtual void Dune::Multiscale::Problem::ZeroNeumannData::evaluate (const DomainType & , RangeType & y) const inline final virtual
Implements Dune::Multiscale::Problem::NeumannDataBase.
virtual std::pair<CommonTraits::DomainType, CommonTraits::DomainType> Dune::Multiscale::Problem::IModelProblemData::gridCorners () const inline virtual
Reimplemented in Dune::Multiscale::Problem::Random::ModelProblemData, Dune::Multiscale::Problem::Synthetic::ModelProblemData, Dune::Multiscale::Problem::SPE10::ModelProblemData, and Dune::Multiscale::Problem::Tarbert::ModelProblemData.
Referenced by Dune::Multiscale::LocalGridList::LocalGridList(), and setup().
virtual bool Dune::Multiscale::Problem::IModelProblemData::hasExactSolution () const inline virtual
does the problem implement an exact solution?
Reimplemented in Dune::Multiscale::Problem::Random::ModelProblemData, Dune::Multiscale::Problem::Synthetic::ModelProblemData, Dune::Multiscale::Problem::SPE10::ModelProblemData, and Dune::Multiscale::Problem::Tarbert::ModelProblemData.
Referenced by data_output(), Dune::Multiscale::print_info(), and Dune::Multiscale::write_discrete_function().
Dune::Multiscale::Problem::IModelProblemData::IModelProblemData (MPIHelper::MPICommunicator , MPIHelper::MPICommunicator , Dune::XT::Common::Configuration) inline
Constructor for ModelProblemData.
virtual void Dune::Multiscale::Problem::DiffusionBase::init (const ProblemContainer & , MPIHelper::MPICommunicator , MPIHelper::MPICommunicator) inline virtual
call this once per grid setup
Reimplemented in Dune::Multiscale::Problem::Random::Diffusion.
Referenced by Dune::Multiscale::Problem::Random::ModelProblemData::problem_init().
void Dune::Multiscale::Problem::DiffusionBase::jacobianDiffusiveFlux (const DomainType & x, const Problem::JacobianRangeType & , const Problem::JacobianRangeType & direction_gradient, Problem::JacobianRangeType & flux) const virtual
the jacobian matrix (JA^{}) of the diffusion operator A^{} at the position "\nabla v" in direction "nabla w", i.e. jacobian diffusiv flux = JA^{}(v) nabla w: jacobianDiffusiveFlux = A^{}(x , position_gradient) direction_gradient
Reimplemented in Dune::Multiscale::Problem::Thirteen::Diffusion.
virtual bool Dune::Multiscale::Problem::IModelProblemData::linear () const inline virtual
linear/nonlinear toggle
Referenced by Dune::Multiscale::print_info().
virtual size_t Dune::Multiscale::Problem::DiffusionBase::order () const inline virtual
Reimplemented in Dune::Multiscale::Problem::Random::Diffusion, and Dune::Multiscale::Problem::Synthetic::Diffusion.
Referenced by Dune::Multiscale::MsFEMCodim0Integral::apply(), and Dune::Multiscale::RhsCodim0Integral::apply().
virtual size_t Dune::Multiscale::Problem::DirichletDataBase::order () const inline virtual
Reimplemented in Dune::Multiscale::Problem::ZeroDirichletData.
virtual size_t Dune::Multiscale::Problem::ZeroDirichletData::order () const inline virtual
Reimplemented from Dune::Multiscale::Problem::DirichletDataBase.
virtual size_t Dune::Multiscale::Problem::NeumannDataBase::order () const inline virtual
Reimplemented in Dune::Multiscale::Problem::ZeroNeumannData.
virtual size_t Dune::Multiscale::Problem::ZeroNeumannData::order () const inline virtual
Reimplemented from Dune::Multiscale::Problem::NeumannDataBase.
virtual void Dune::Multiscale::Problem::DiffusionBase::prepare_new_evaluation () inline virtual
call this once per "run"
Reimplemented in Dune::Multiscale::Problem::Random::Diffusion.
Referenced by Dune::Multiscale::Problem::Random::ModelProblemData::prepare_new_evaluation().
virtual void Dune::Multiscale::Problem::IModelProblemData::prepare_new_evaluation (DMP::ProblemContainer &) inline virtual
call this once per "run"
Reimplemented in Dune::Multiscale::Problem::Random::ModelProblemData.
Referenced by Dune::Multiscale::cgfem_algorithm(), main(), and Dune::Multiscale::msfem_algorithm().
virtual void Dune::Multiscale::Problem::IModelProblemData::problem_init (DMP::ProblemContainer & , MPIHelper::MPICommunicator , MPIHelper::MPICommunicator) inline virtual
call this once per grid setup
Reimplemented in Dune::Multiscale::Problem::Random::ModelProblemData.
Referenced by Dune::Multiscale::Problem::ProblemContainer::ProblemContainer().
virtual const SubBoundaryInfoType& Dune::Multiscale::Problem::IModelProblemData::subBoundaryInfo () const pure virtual
Implemented in Dune::Multiscale::Problem::Random::ModelProblemData, Dune::Multiscale::Problem::Synthetic::ModelProblemData, Dune::Multiscale::Problem::SPE10::ModelProblemData, and Dune::Multiscale::Problem::Tarbert::ModelProblemData.
virtual bool Dune::Multiscale::Problem::IModelProblemData::symmetricDiffusion () const inline virtual
is the diffusion matrix symmetric?
virtual Dune::Multiscale::Problem::DiffusionBase::~DiffusionBase () inline virtual
virtual Dune::Multiscale::Problem::IModelProblemData::~IModelProblemData () inline virtual