msfem.cc File Reference
msfem.cc File Reference
#include <config.h>
#include "msfem.hh"
#include <dune/multiscale/common/main_init.hh>
#include <dune/multiscale/msfem/localsolution_proxy.hh>
#include <dune/multiscale/msfem/localproblems/localgridlist.hh>
#include <dune/multiscale/problems/base.hh>
#include <dune/multiscale/common/grid_creation.hh>
#include <dune/multiscale/msfem/msfem_solver.hh>
#include <dune/multiscale/msfem/fem_solver.hh>
#include <dune/multiscale/msfem/msfem_traits.hh>
#include <dune/multiscale/common/heterogenous.hh>
#include <dune/stuff/common/ranges.hh>
#include <dune/stuff/grid/walker/functors.hh>
#include <dune/stuff/grid/walker/apply-on.hh>
#include <dune/stuff/common/profiler.hh>
#include <dune/stuff/common/logging.hh>
#include <dune/stuff/common/configuration.hh>
#include <dune/stuff/common/signals.hh>
#include <dune/gdt/products/h1.hh>
#include <dune/gdt/products/weightedl2.hh>
#include <dune/gdt/products/boundaryl2.hh>
#include <boost/filesystem.hpp>
Functions
double surface_flow_gdt (const Dune::Multiscale::CommonTraits::GridType &grid, const Dune::Multiscale::CommonTraits::ConstDiscreteFunctionType &solution, const DMP::ProblemContainer &problem)
void set_config_values (const std::vector< std::string > &keys, const std::vector< std::string > &values)
workaround for https://github.com/wwu-numerik/dune-stuff/issues/42
void handle_sigterm (int)
Function Documentation
void handle_sigterm (int)
Referenced by MultiLevelMonteCarlo::msfem_init().
void set_config_values (const std::vector< std::string > & keys, const std::vector< std::string > & values)
workaround for https://github.com/wwu-numerik/dune-stuff/issues/42
Referenced by MultiLevelMonteCarlo::msfem_init().
double surface_flow_gdt (const Dune::Multiscale::CommonTraits::GridType & grid, const Dune::Multiscale::CommonTraits::ConstDiscreteFunctionType & solution, const DMP::ProblemContainer & problem)
Referenced by MultiLevelMonteCarlo::MsCgFemDifference::compute_inflow_difference().