MultiLevelMonteCarlo Namespace Reference
MultiLevelMonteCarlo Namespace Reference
Classes
class Single
class Fast
class Medium
class Slow
class Difference
class Level
Class for doing statistics on a given level.
class MLMC
class MsCgFemDifference
class MsFemSingleDifference
Functions
static void check (bool condition, const char *message)
static bool isPowerOf2 (int x)
void msfem_init (int argc, char **argv)
Function Documentation
static void MultiLevelMonteCarlo::check (bool condition, const char * message) static
Terminates program if condition is not satisfied.
Parameters
condition condition to check
message message to show when condition is false TODO embed into exception handling
Referenced by MultiLevelMonteCarlo::MLMC::addDifference(), MultiLevelMonteCarlo::Level::assignProcessors(), MultiLevelMonteCarlo::MLMC::expectation(), and MultiLevelMonteCarlo::Level::Level().
static bool MultiLevelMonteCarlo::isPowerOf2 (int x) static
Checks for power of 2
Parameters
x number to check
Referenced by MultiLevelMonteCarlo::MLMC::addDifference(), and MultiLevelMonteCarlo::MLMC::expectation().
void MultiLevelMonteCarlo::msfem_init (int argc, char ** argv)
References handle_sigterm(), and set_config_values().