MultiLevelMonteCarlo::MLMC Class Reference
MultiLevelMonteCarlo::MLMC Class Reference
#include <dune/mlmc/mlmc.hh>
Public Member Functions
void addDifference (const std::shared_ptr< Difference > diff, int minProc)
void setRepetitions (double tol)
double expectation (double tol, int nBreak, MPI_Comm world=MPI_COMM_WORLD)
Detailed Description
Environment for computing expected values by the Multi Level Monte Carlo Method.
Member Function Documentation
void MultiLevelMonteCarlo::MLMC::addDifference (const std::shared_ptr< Difference > diff, int minProc) inline
Adds difference object.
Parameters
diff Difference object
minProc minimal number of processors needed to compute solution
References MultiLevelMonteCarlo::check(), and MultiLevelMonteCarlo::isPowerOf2().
double MultiLevelMonteCarlo::MLMC::expectation (double tol, int nBreak, MPI_Comm world = MPI_COMM_WORLD) inline
Computes the expected value of a scalar random variable up to a given tolerance by the Multi Level Monte Carlo approach.
Parameters
tol absolute tolerance of expected value
nBreak number of breaks for recomputing required realizations
References MultiLevelMonteCarlo::check(), MultiLevelMonteCarlo::Level::eval(), MultiLevelMonteCarlo::Level::getGroup(), MultiLevelMonteCarlo::Level::getMasters(), MultiLevelMonteCarlo::Level::groups(), MultiLevelMonteCarlo::Level::isMaster(), MultiLevelMonteCarlo::isPowerOf2(), MultiLevelMonteCarlo::Level::nextRepetitions(), MultiLevelMonteCarlo::Level::procs(), setRepetitions(), and MultiLevelMonteCarlo::Level::update().
void MultiLevelMonteCarlo::MLMC::setRepetitions (double tol) inline
Computes optimal number of repetitions per level .
Parameters
tol absolute tolerance of expected value
Referenced by expectation().
The documentation for this class was generated from the following file:
mlmc.hh