MultiLevelMonteCarlo::Level Class Reference
MultiLevelMonteCarlo::Level Class Reference
Class for doing statistics on a given level.
#include <dune/mlmc/mlmc.hh>
Public Member Functions
Level ()
Constructs empty level.
Level (const std::shared_ptr< Difference > diff, int minProc=1)
void assignProcessors (MPI_Comm world=MPI_COMM_WORLD)
void setRepetitions (int N)
int getRepetitions () const
Gets number of repetitions.
int nextRepetitions (int iBreak, int nBreak) const
MPI_Comm getMasters () const
Returns communicator of masters.
bool isMaster () const
Indicates master.
MPI_Comm getGroup () const
Returns communicator of masters.
void clear ()
Clears statistics.
void update (int n, double sumX, double sumX2, double T)
Updates statistics.
double mean () const
Returns mean value of realizations on present level.
double var () const
Returns empirical variance of realizations on present level.
double time () const
Returns average time of repetition on present level.
int groups () const
Returns number of groups on present level.
int procs () const
Return number of processors per group.
double eval ()
Evaluate difference.
Detailed Description
Class for doing statistics on a given level.
Constructor & Destructor Documentation
MultiLevelMonteCarlo::Level::Level () inline
Constructs empty level.
MultiLevelMonteCarlo::Level::Level (const std::shared_ptr< Difference > diff, int minProc = 1) inline
Constructs level from Difference object.
Parameters
diff Difference object
minProc minimal number of processors needed to compute solution
References MultiLevelMonteCarlo::check().
Member Function Documentation
void MultiLevelMonteCarlo::Level::assignProcessors (MPI_Comm world = MPI_COMM_WORLD) inline
Assigns communicator and group
Parameters
world global communicator
References MultiLevelMonteCarlo::check().
void MultiLevelMonteCarlo::Level::clear () inline
Clears statistics.
double MultiLevelMonteCarlo::Level::eval () inline
Evaluate difference.
Referenced by MultiLevelMonteCarlo::MLMC::expectation().
MPI_Comm MultiLevelMonteCarlo::Level::getGroup () const inline
Returns communicator of masters.
Referenced by MultiLevelMonteCarlo::MLMC::expectation().
MPI_Comm MultiLevelMonteCarlo::Level::getMasters () const inline
Returns communicator of masters.
Referenced by MultiLevelMonteCarlo::MLMC::expectation().
int MultiLevelMonteCarlo::Level::getRepetitions () const inline
Gets number of repetitions.
int MultiLevelMonteCarlo::Level::groups () const inline
Returns number of groups on present level.
Referenced by MultiLevelMonteCarlo::MLMC::expectation().
bool MultiLevelMonteCarlo::Level::isMaster () const inline
Indicates master.
Referenced by MultiLevelMonteCarlo::MLMC::expectation().
double MultiLevelMonteCarlo::Level::mean () const inline
Returns mean value of realizations on present level.
Referenced by var().
int MultiLevelMonteCarlo::Level::nextRepetitions (int iBreak, int nBreak) const inline
Returns number of repetitions till next break.
Parameters
iBreak index of next break
nBreak total number of breaks
Referenced by MultiLevelMonteCarlo::MLMC::expectation().
int MultiLevelMonteCarlo::Level::procs () const inline
Return number of processors per group.
Referenced by MultiLevelMonteCarlo::MLMC::expectation().
void MultiLevelMonteCarlo::Level::setRepetitions (int N) inline
Sets number of repetitions.
Parameters
N number of repetitions
double MultiLevelMonteCarlo::Level::time () const inline
Returns average time of repetition on present level.
void MultiLevelMonteCarlo::Level::update (int n, double sumX, double sumX2, double T) inline
Updates statistics.
Referenced by MultiLevelMonteCarlo::MLMC::expectation().
double MultiLevelMonteCarlo::Level::var () const inline
Returns empirical variance of realizations on present level.
References mean().
The documentation for this class was generated from the following file:
mlmc.hh